version: "3"

services:
  kvs:
    image: redis
    ports:
      - 6379:6379
  
  server:
    build: server
    volumes:
      - ./server:/code:ro
    ports:
      - 8765:8765
    
    depends_on:
      - kvs
