version: "3"

services:
  kvs:
    image: redis
    ports:
      - 6379:6379
  
  pod_server:
    build: server
    ports:
      - 8765:8765
    
    depends_on:
      - kvs
  
  front_server:
    build: front
    volumes:
      - ./front:/code:ro
    ports:
      - 8080:80
